# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcredstash < Formula
  desc "Manages credentials using AWS Key Management Service (KMS) and DynamoDB"
  homepage "https://github.com/kgaughan/gcredstash"
  version "0.5.1"
  license "ASL 2.0"

  on_macos do
    on_intel do
      url "https://github.com/kgaughan/gcredstash/releases/download/v0.5.1/gcredstash_0.5.1_darwin_x86_64.tar.gz"
      sha256 "1b41a806e930961b45dff793f6d0baf9470d72b18d36f7a1c3382ca193bc60fd"

      def install
        bin.install "gcredstash"
      end
    end
    on_arm do
      url "https://github.com/kgaughan/gcredstash/releases/download/v0.5.1/gcredstash_0.5.1_darwin_arm64.tar.gz"
      sha256 "b3ffe64045e988ef0f99c978d623acba950e01b934e6ffef179209c190ba77eb"

      def install
        bin.install "gcredstash"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kgaughan/gcredstash/releases/download/v0.5.1/gcredstash_0.5.1_linux_x86_64.tar.gz"
        sha256 "0fba4d384d59a3c9548bf548170c577c83159079bfbec05655328317a04fccbd"

        def install
          bin.install "gcredstash"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kgaughan/gcredstash/releases/download/v0.5.1/gcredstash_0.5.1_linux_arm64.tar.gz"
        sha256 "215638bab85233481b3380439bd75c444fc7fbeaef345da5f8f999ca3d0b9c72"

        def install
          bin.install "gcredstash"
        end
      end
    end
  end
end
