# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nibbled < Formula
  desc "A server for the Gopher protocol"
  homepage "https://github.com/kgaughan/nibbled"
  version "0.2.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kgaughan/nibbled/releases/download/v0.2.2/nibbled_0.2.2_darwin_x86_64.tar.gz"
      sha256 "d29f55de4404dcbb91e9a95dca56da1cdf7baf340ee76c11c30d63a2bded17b6"

      def install
        bin.install "nibbled"
        man1.install "nibbled.1"
      end
    end
    on_arm do
      url "https://github.com/kgaughan/nibbled/releases/download/v0.2.2/nibbled_0.2.2_darwin_arm64.tar.gz"
      sha256 "5b6faf9efb7381ac27b8cb02a8032e953643a90d4642c714be851c38dc65b8af"

      def install
        bin.install "nibbled"
        man1.install "nibbled.1"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kgaughan/nibbled/releases/download/v0.2.2/nibbled_0.2.2_linux_x86_64.tar.gz"
        sha256 "396307466340d96df5af30f085a416146622ac28bffde45f6d47d4538ab99353"

        def install
          bin.install "nibbled"
          man1.install "nibbled.1"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kgaughan/nibbled/releases/download/v0.2.2/nibbled_0.2.2_linux_arm64.tar.gz"
        sha256 "14ebce5d82d5bc5cc4aac1426489e5a224aa5a13ea6c67755a199ed02c5ea49f"

        def install
          bin.install "nibbled"
          man1.install "nibbled.1"
        end
      end
    end
  end
end
