# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nibbled < Formula
  desc "A server for the Gopher protocol"
  homepage "https://github.com/kgaughan/nibbled"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kgaughan/nibbled/releases/download/v0.1.0/nibbled_0.1.0_darwin_x86_64.tar.gz"
      sha256 "132d49462f989b8aa9d8ab9ffd7ba88651ab25e62a4b5710a94eafb58927153f"

      def install
        bin.install "nibbled"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kgaughan/nibbled/releases/download/v0.1.0/nibbled_0.1.0_darwin_arm64.tar.gz"
      sha256 "8e9c0a5e05964794fa4e94a55c4b69bc1728b978422fdfde8f104d622239bdac"

      def install
        bin.install "nibbled"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kgaughan/nibbled/releases/download/v0.1.0/nibbled_0.1.0_linux_x86_64.tar.gz"
      sha256 "c4bcd8d781d4e045bd2815455184a7b6f679f3110934280dfdb65d09e0db4797"

      def install
        bin.install "nibbled"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kgaughan/nibbled/releases/download/v0.1.0/nibbled_0.1.0_linux_arm64.tar.gz"
      sha256 "cdcc93c2ad986ee52eebfd26ad987ef5750a959be63fc808dad473082554ea1e"

      def install
        bin.install "nibbled"
      end
    end
  end
end
