# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nibbled < Formula
  desc "A server for the Gopher protocol"
  homepage "https://github.com/kgaughan/nibbled"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kgaughan/nibbled/releases/download/v0.2.1/nibbled_0.2.1_darwin_x86_64.tar.gz"
      sha256 "00c6bc2aedfab25b49554b3181cc8886448a4be39bb34f2195a223dd5271b355"

      def install
        bin.install "nibbled"
        man1.install "nibbled.1"
      end
    end
    on_arm do
      url "https://github.com/kgaughan/nibbled/releases/download/v0.2.1/nibbled_0.2.1_darwin_arm64.tar.gz"
      sha256 "b0946e1670927472b7d72c2fae5505b5d40ea92cbe95b2b3cea6d48247f6fd49"

      def install
        bin.install "nibbled"
        man1.install "nibbled.1"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kgaughan/nibbled/releases/download/v0.2.1/nibbled_0.2.1_linux_x86_64.tar.gz"
        sha256 "a2ecae0d4f531b8c502b5fe413793b20dc2168af3b9c66b30ec7b8be7716e939"

        def install
          bin.install "nibbled"
          man1.install "nibbled.1"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kgaughan/nibbled/releases/download/v0.2.1/nibbled_0.2.1_linux_arm64.tar.gz"
        sha256 "22e6649abbcf2ede497d61b102acb7a08e330c59ac2d5306e5f39a6368578f6b"

        def install
          bin.install "nibbled"
          man1.install "nibbled.1"
        end
      end
    end
  end
end
