# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nxtp < Formula
  desc " A Network neXt Time Protocol (NXTP) client and server"
  homepage "https://github.com/kgaughan/nxtp"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kgaughan/nxtp/releases/download/v1.0.4/nxtp_1.0.4_darwin_x86_64.tar.gz"
      sha256 "b27ad55df6c2fa8e92e4234ed7ecc32e14f7cf902dbfece45852b52989ab1f43"

      def install
        bin.install "nxtp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kgaughan/nxtp/releases/download/v1.0.4/nxtp_1.0.4_darwin_arm64.tar.gz"
      sha256 "44d6abf9572ef03ddcead884306cd121b506990c713dd5e7ce39e1ac7604bfb4"

      def install
        bin.install "nxtp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kgaughan/nxtp/releases/download/v1.0.4/nxtp_1.0.4_linux_x86_64.tar.gz"
      sha256 "ae2554cdaab6480ce6bf4d0143a739a27f1c4a8a4847cb3a5056710c65a8eec5"
      def install
        bin.install "nxtp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kgaughan/nxtp/releases/download/v1.0.4/nxtp_1.0.4_linux_arm64.tar.gz"
      sha256 "8f75ccb41aa71f19441e6907d1cd442fd5428c2c5b09ff47104ca3f5faf29da8"
      def install
        bin.install "nxtp"
      end
    end
  end
end
