# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nxtp < Formula
  desc " A Network neXt Time Protocol (NXTP) client and server"
  homepage "https://github.com/kgaughan/nxtp"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kgaughan/nxtp/releases/download/v1.0.4/nxtp_1.0.4_darwin_x86_64.tar.gz"
      sha256 "e3d41f2f0db8e7a0f16524cd3b6ec778aa0765b20fbc4b94b43355a1998c9b62"

      def install
        bin.install "nxtp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kgaughan/nxtp/releases/download/v1.0.4/nxtp_1.0.4_darwin_arm64.tar.gz"
      sha256 "254dbe091b4005dc245df4b4bd6061059a6026f1da80584fd707e9feccaf4a6e"

      def install
        bin.install "nxtp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kgaughan/nxtp/releases/download/v1.0.4/nxtp_1.0.4_linux_x86_64.tar.gz"
      sha256 "932f30fa4e6c975838e5d6edb830252bc8a5545eda1222de3e797e76a26822fc"
      def install
        bin.install "nxtp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kgaughan/nxtp/releases/download/v1.0.4/nxtp_1.0.4_linux_arm64.tar.gz"
      sha256 "4ddd0026f0af5518ab898a027e467fa04d605fadde481d3c769655aeaa154c06"
      def install
        bin.install "nxtp"
      end
    end
  end
end
