# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nxtp < Formula
  desc " A Network neXt Time Protocol (NXTP) client and server"
  homepage "https://github.com/kgaughan/nxtp"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kgaughan/nxtp/releases/download/v1.0.3/nxtp_1.0.3_darwin_x86_64.tar.gz"
      sha256 "c75ab48f576a8c52cc4b965e64af1a4a9116d81faf80a23be37b5b87d089358e"

      def install
        bin.install "nxtp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kgaughan/nxtp/releases/download/v1.0.3/nxtp_1.0.3_darwin_arm64.tar.gz"
      sha256 "0e26186be4745b84c329a1bc491d9886af82f15fc39493944e5229c62215daca"

      def install
        bin.install "nxtp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kgaughan/nxtp/releases/download/v1.0.3/nxtp_1.0.3_linux_x86_64.tar.gz"
        sha256 "d0b59e9f59f80cc58bb921a76f511ed386cd5b20dc1e57610fa1d62fc51a5fcc"

        def install
          bin.install "nxtp"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kgaughan/nxtp/releases/download/v1.0.3/nxtp_1.0.3_linux_arm64.tar.gz"
        sha256 "8e92b13d28920c311f2d1774ba1f872198a8e97679195cf4669caf7513a3c781"

        def install
          bin.install "nxtp"
        end
      end
    end
  end
end
