# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlanetMercury < Formula
  desc "A Planet-style feed aggregator"
  homepage "https://github.com/kgaughan/mercury"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kgaughan/mercury/releases/download/v0.3.2/mercury_0.3.2_darwin_x86_64.tar.gz"
      sha256 "78fbe6b4339877e0b39f2f8734d5840e9330598deaadca72974b3f4bae0fe6aa"

      def install
        bin.install "mercury"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kgaughan/mercury/releases/download/v0.3.2/mercury_0.3.2_darwin_arm64.tar.gz"
      sha256 "03f409ffd021e8bb971a22d7c827a352db9a1ea283c52cc700c864684193c15e"

      def install
        bin.install "mercury"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kgaughan/mercury/releases/download/v0.3.2/mercury_0.3.2_linux_arm64.tar.gz"
      sha256 "1ce7ca8dcc3552dfa0ab4503e93833625b520130b69bc2b601e36dce6d00b8ea"

      def install
        bin.install "mercury"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kgaughan/mercury/releases/download/v0.3.2/mercury_0.3.2_linux_x86_64.tar.gz"
      sha256 "7e17dad887066a914f41113f2e3eefc6f96dcfea68362b3a22d943962041a360"

      def install
        bin.install "mercury"
      end
    end
  end
end
