# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlanetMercury < Formula
  desc "A Planet-style feed aggregator"
  homepage "https://github.com/kgaughan/mercury"
  version "0.4.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kgaughan/mercury/releases/download/v0.4.1/mercury_0.4.1_darwin_x86_64.tar.gz"
      sha256 "64dbaf253ab0ae7c2d337c391172110e26c50d01a1447680a1750a10545f50d3"

      def install
        bin.install "mercury"
      end
    end
    on_arm do
      url "https://github.com/kgaughan/mercury/releases/download/v0.4.1/mercury_0.4.1_darwin_arm64.tar.gz"
      sha256 "50da4e3c49787f642ad852032997648fa5fa499e7648d83d2aac17bd60adbe2d"

      def install
        bin.install "mercury"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kgaughan/mercury/releases/download/v0.4.1/mercury_0.4.1_linux_x86_64.tar.gz"
        sha256 "28da5d7ee1eaa91008082dee81c31d94db10117efde1f624b7dd655dac1700f4"

        def install
          bin.install "mercury"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kgaughan/mercury/releases/download/v0.4.1/mercury_0.4.1_linux_arm64.tar.gz"
        sha256 "eefd9cc99b2aa112d33c0a251436dd63d98989dddb0e2770a65d6ecf122bae36"

        def install
          bin.install "mercury"
        end
      end
    end
  end
end
