# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlanetMercury < Formula
  desc "A Planet-style feed aggregator"
  homepage "https://github.com/kgaughan/mercury"
  version "0.4.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kgaughan/mercury/releases/download/v0.4.1/mercury_0.4.1_darwin_x86_64.tar.gz"
      sha256 "62c5dd42ac72394feb6c38effbc0d068bacfff46c219df59640ce408f727e6a3"

      def install
        bin.install "mercury"
      end
    end
    on_arm do
      url "https://github.com/kgaughan/mercury/releases/download/v0.4.1/mercury_0.4.1_darwin_arm64.tar.gz"
      sha256 "bce56945257b51153a61922aba5f8a78ef6da4d96ab6f0a4a8e2f06ac03ffa6e"

      def install
        bin.install "mercury"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kgaughan/mercury/releases/download/v0.4.1/mercury_0.4.1_linux_x86_64.tar.gz"
        sha256 "09ff3ec4abc0c0d95ea183582ee3a72a06b6c0d53490341e7977e1cafc511297"

        def install
          bin.install "mercury"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kgaughan/mercury/releases/download/v0.4.1/mercury_0.4.1_linux_arm64.tar.gz"
        sha256 "d1b986a3b52e7102a787116325235d3b0c9b0f23503bf0b5470efe594cab3fc0"

        def install
          bin.install "mercury"
        end
      end
    end
  end
end
