# This file was generated by GoReleaser. DO NOT EDIT.
cask "gcredstash" do
  name "gcredstash"
  desc "Manages credentials using AWS Key Management Service (KMS) and DynamoDB"
  homepage "https://github.com/kgaughan/gcredstash"
  version "0.6.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gcredstash"

  on_macos do
    on_intel do
      url "https://github.com/kgaughan/gcredstash/releases/download/v#{version}/gcredstash_#{version}_darwin_x86_64.tar.gz"
      sha256 "6ee79fa33df591f9364009c19bcbc14aa53742e4d1df68c54dd36d0767038746"
    end
    on_arm do
      url "https://github.com/kgaughan/gcredstash/releases/download/v#{version}/gcredstash_#{version}_darwin_arm64.tar.gz"
      sha256 "9d954461349748f0571400188a57fed1db8e4d94350ded9f15b50f5b158a380a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kgaughan/gcredstash/releases/download/v#{version}/gcredstash_#{version}_linux_x86_64.tar.gz"
      sha256 "43a1b9b813e2fcb477e7fa9f0e791b9c9b7f099bb4f232348021b640edced5cc"
    end
    on_arm do
      url "https://github.com/kgaughan/gcredstash/releases/download/v#{version}/gcredstash_#{version}_linux_arm64.tar.gz"
      sha256 "65a4e610fbd0b7f5f3c9209040cfa66ebc83f1b692c9352d6ad1a6d537a5f0c2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gcredstash"]
    end
  end

  # No zap stanza required
end
