# This file was generated by GoReleaser. DO NOT EDIT.
cask "gcredstash" do
  version "0.6.10"

  on_macos do
    on_intel do
      sha256 "ef9745aa522c94d5846a423f1e438d1d4635fe2abe3d0e3ca047444b6d89ca69"
      url "https://github.com/kgaughan/gcredstash/releases/download/v#{version}/gcredstash_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d17b74e499c8be1987bb954324d2c948b7d5164227f10370cdb86326840f770e"
      url "https://github.com/kgaughan/gcredstash/releases/download/v#{version}/gcredstash_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fb52c307a2b6373eb67a9db9f6b76304116f32ded9841823185042b129967e97"
      url "https://github.com/kgaughan/gcredstash/releases/download/v#{version}/gcredstash_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1bd74901a52846ca37e4eeeacdf9633f3d4c1b8a46b0b39d7edd974305d29c2b"
      url "https://github.com/kgaughan/gcredstash/releases/download/v#{version}/gcredstash_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gcredstash"
  desc "Manages credentials using AWS Key Management Service (KMS) and DynamoDB"
  homepage "https://github.com/kgaughan/gcredstash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gcredstash"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gcredstash"]
    end
  end

  # No zap stanza required

end
