# This file was generated by GoReleaser. DO NOT EDIT.
cask "gcredstash" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gcredstash"]
    end
  end

  version "0.6.15"

  on_macos do
    on_arm do
      sha256 "a6b943beb282dfe30419099a12a308a54a53939050a62629b50cf534ab66b267"
      url "https://github.com/kgaughan/gcredstash/releases/download/v#{version}/gcredstash_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c57490c340bfd0baeed14095a41457a348f8323b5cdb9c2686b8bc189d33378c"
      url "https://github.com/kgaughan/gcredstash/releases/download/v#{version}/gcredstash_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "028980c50276f1840153aa3ef19dac0718eff3ed68fd06aa6528b653f3fd95b0"
      url "https://github.com/kgaughan/gcredstash/releases/download/v#{version}/gcredstash_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "845fcef681ab636fa1adeb6fc7e2b1efc4b4363b505c36f09f587cd68c98f71e"
      url "https://github.com/kgaughan/gcredstash/releases/download/v#{version}/gcredstash_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "gcredstash"
  desc "Manages credentials using AWS Key Management Service (KMS) and DynamoDB"
  homepage "https://github.com/kgaughan/gcredstash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gcredstash"

  # No zap stanza required
end
