# This file was generated by GoReleaser. DO NOT EDIT.
cask "nibbled" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/nibbled"]
    end
  end

  version "0.2.4"

  on_macos do
    on_arm do
      sha256 "2d45d3f1507653d61b7546ba05339c540f7bf979eef018a129473fd02346f180"
      url "https://github.com/kgaughan/nibbled/releases/download/v#{version}/nibbled_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bd0f0c2dd0a9f8d8cf037b7e4a9529c45ad94bad5966550dcedb0c6a8f536e2d"
      url "https://github.com/kgaughan/nibbled/releases/download/v#{version}/nibbled_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "73dd50be79999bb54146dde665b9f0e4a307a37cdbaf4048f27c1982b5a05abf"
      url "https://github.com/kgaughan/nibbled/releases/download/v#{version}/nibbled_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "37affecda65f0b967414173b9fe77e546dc78fe76ccdcf0121c31d99080a1841"
      url "https://github.com/kgaughan/nibbled/releases/download/v#{version}/nibbled_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "nibbled"
  desc "A server for the Gopher protocol"
  homepage "https://github.com/kgaughan/nibbled"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nibbled"
  manpage "nibbled.1"

  # No zap stanza required
end
