# This file was generated by GoReleaser. DO NOT EDIT.
cask "nibbled" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "0732cebd28f7e6555a9af72204913288cf6281c4e7f4bcce9df41c819e59bbd9"
      url "https://github.com/kgaughan/nibbled/releases/download/v#{version}/nibbled_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e02c3f118891ccbf640ad0ad092a14217f9f371c196ec4bb8747c6628936cc7f"
      url "https://github.com/kgaughan/nibbled/releases/download/v#{version}/nibbled_#{version}_darwin_arm64.tar.gz"
    end
  end
  on_linux do
    on_intel do
      sha256 "401f7bddd9d4c38e0d9c38b2975780c6d495ef421818a0c5549bd4295630b7ac"
      url "https://github.com/kgaughan/nibbled/releases/download/v#{version}/nibbled_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "16b8276dd1ed2ea73df2bc01c65f0f357db2c1796cbb20d3a903eccc7ebfd4bf"
      url "https://github.com/kgaughan/nibbled/releases/download/v#{version}/nibbled_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nibbled"
  desc "A server for the Gopher protocol"
  homepage "https://github.com/kgaughan/nibbled"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nibbled"
  manpage "nibbled.1"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/nibbled"]
    end
  end

  # No zap stanza required
end
