# This file was generated by GoReleaser. DO NOT EDIT.
cask "nxtp" do
  version "1.0.5"

  on_macos do
    on_intel do
      sha256 "8327f5bc3a8177a1d80d47956f622f637a05ba1d5676622de87c884cc76808bf"
      url "https://github.com/kgaughan/nxtp/releases/download/v#{version}/nxtp_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "03f332de5683350ff3e1a46ee7d048aab60d2ce2cad8e39453f2c66990b234e9"
      url "https://github.com/kgaughan/nxtp/releases/download/v#{version}/nxtp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "96d74641bdeda35be5dbb006aa1b45c6a347deab31ec952c304bc84fca7b3d48"
      url "https://github.com/kgaughan/nxtp/releases/download/v#{version}/nxtp_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3a423945c0389b3718fd6215a44819dbed65f8064e21e94be92e26439ea45151"
      url "https://github.com/kgaughan/nxtp/releases/download/v#{version}/nxtp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nxtp"
  desc " A Network neXt Time Protocol (NXTP) client and server"
  homepage "https://github.com/kgaughan/nxtp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nxtp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nxtp"]
    end
  end

  # No zap stanza required

end
