# This file was generated by GoReleaser. DO NOT EDIT.
cask "nxtp" do
  name "nxtp"
  desc " A Network neXt Time Protocol (NXTP) client and server"
  homepage "https://github.com/kgaughan/nxtp"
  version "1.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nxtp"

  on_macos do
    on_intel do
      url "https://github.com/kgaughan/nxtp/releases/download/v#{version}/nxtp_#{version}_darwin_x86_64.tar.gz"
      sha256 "151e8be4a27616f055a1b6522c8874311ce372c17dfc2c1a4e729a7515104970"
    end
    on_arm do
      url "https://github.com/kgaughan/nxtp/releases/download/v#{version}/nxtp_#{version}_darwin_arm64.tar.gz"
      sha256 "9901889d755bf31747f1571cebe00d642f05ad125b1f50325e63437829f620ee"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kgaughan/nxtp/releases/download/v#{version}/nxtp_#{version}_linux_x86_64.tar.gz"
      sha256 "228707b39fbb604320f45562033c0d9be5c45b6a95f376d314edcea8e216ae87"
    end
    on_arm do
      url "https://github.com/kgaughan/nxtp/releases/download/v#{version}/nxtp_#{version}_linux_arm64.tar.gz"
      sha256 "b35c6767d04c57e3179fe07bf58af3903f1716206b82d92cdfe582361330223a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nxtp"]
    end
  end

  # No zap stanza required
end
