# This file was generated by GoReleaser. DO NOT EDIT.
cask "nxtp" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/nxtp"]
    end
  end

  version "1.0.7"

  on_macos do
    on_arm do
      sha256 "256eb0659e72266ae06e1ec8c4cdeee4ddaedc424affc1475d218ecbf44a9621"
      url "https://github.com/kgaughan/nxtp/releases/download/v#{version}/nxtp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3bc06ef59a1073cfe53a964d94c1a32a476f804d9d6f35f537daec55b29aebdb"
      url "https://github.com/kgaughan/nxtp/releases/download/v#{version}/nxtp_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "79105c51cc10f087cb6e94daccf80091794b146db38505afba7fef84dd5de280"
      url "https://github.com/kgaughan/nxtp/releases/download/v#{version}/nxtp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0d14e2bbb4a32a1f2f52e24bb74509a95ff095aab6aab992f092b76935279f56"
      url "https://github.com/kgaughan/nxtp/releases/download/v#{version}/nxtp_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "nxtp"
  desc " A Network neXt Time Protocol (NXTP) client and server"
  homepage "https://github.com/kgaughan/nxtp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nxtp"

  # No zap stanza required
end
