# This file was generated by GoReleaser. DO NOT EDIT.
cask "planet-mercury" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/mercury"]
    end
  end

  version "0.7.1"

  on_macos do
    on_arm do
      sha256 "3c7c52a10fe3da0ed99c2115dedbc80917b4cd9c36452ae7664d0ac88fe59392"
      url "https://github.com/kgaughan/mercury/releases/download/v#{version}/mercury_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d7a481669d10be18bce70cd2ba00a92fa45fd0ac3064df743da91cba3ff710e8"
      url "https://github.com/kgaughan/mercury/releases/download/v#{version}/mercury_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2a99e20c6e454ce3d939445c9f08c7559f97458a41cfd5553115aa9996fe4fb3"
      url "https://github.com/kgaughan/mercury/releases/download/v#{version}/mercury_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "19568cc0f131b66075459c95326fec2e3bb6a36de6dd7205509e3f9c33c9e401"
      url "https://github.com/kgaughan/mercury/releases/download/v#{version}/mercury_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "planet-mercury"
  desc "A Planet-style feed aggregator"
  homepage "https://github.com/kgaughan/mercury"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "planet-mercury"

  # No zap stanza required
end
