# This file was generated by GoReleaser. DO NOT EDIT.
cask "planet-mercury" do
  name "planet-mercury"
  desc "A Planet-style feed aggregator"
  homepage "https://github.com/kgaughan/mercury"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "planet-mercury"

  on_macos do
    on_intel do
      url "https://github.com/kgaughan/mercury/releases/download/v#{version}/mercury_#{version}_darwin_x86_64.tar.gz"
      sha256 "743b069f282d89feed0d812982fd893f5bb0f6608639e5482844cc7af5f2b76d"
    end
    on_arm do
      url "https://github.com/kgaughan/mercury/releases/download/v#{version}/mercury_#{version}_darwin_arm64.tar.gz"
      sha256 "de0076e6a7917ee531b02899c6e769e193ff85d9480f2cc0b510a0045cfa5a4b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kgaughan/mercury/releases/download/v#{version}/mercury_#{version}_linux_x86_64.tar.gz"
      sha256 "192d703c640a5046128e74f38a697c1e6b8e8d0144c9a5d1e2cd963dc1540405"
    end
    on_arm do
      url "https://github.com/kgaughan/mercury/releases/download/v#{version}/mercury_#{version}_linux_arm64.tar.gz"
      sha256 "6d8b1e33cbd6a1d1a8a3cdc70a0ad3e5ae197c04000611f9c609f31427e0bf46"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mercury"]
    end
  end

  # No zap stanza required
end
