# This file was generated by GoReleaser. DO NOT EDIT.
cask "planet-mercury" do
  name "planet-mercury"
  desc "A Planet-style feed aggregator"
  homepage "https://github.com/kgaughan/mercury"
  version "0.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "planet-mercury"

  on_macos do
    on_intel do
      url "https://github.com/kgaughan/mercury/releases/download/v#{version}/mercury_#{version}_darwin_x86_64.tar.gz"
      sha256 "c0157c49c0513ce233c2ad95743aff086f9bd796a9672e89513f681b1afef4e2"
    end
    on_arm do
      url "https://github.com/kgaughan/mercury/releases/download/v#{version}/mercury_#{version}_darwin_arm64.tar.gz"
      sha256 "d558c9a2a28cd82f63344fe446a900676f51037f7305b8e492e02691f68a3cfc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kgaughan/mercury/releases/download/v#{version}/mercury_#{version}_linux_x86_64.tar.gz"
      sha256 "2570b492aaea510027e4e31f584b7138b5e10881ea67e52cb677a4fadabb0084"
    end
    on_arm do
      url "https://github.com/kgaughan/mercury/releases/download/v#{version}/mercury_#{version}_linux_arm64.tar.gz"
      sha256 "a95efffadadc250789bfaeff125455f07a3b068ef4ab0136c5e7076c64f5fc07"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mercury"]
    end
  end

  # No zap stanza required
end
